### ISSUE TITLE
android 5.1 support

### ISSUE THREAD

**Issue by qmmp123** [dogecv/DogeCV#22]
Can't use library because OpenCV3 uses old API(less 21). Can you update it?

**Comment by qmmp123** [comment]
Sorry, I did not see class JavaCameraBridge2

**Comment by qmmp123** [comment]
Damn! I can't understand how to replace javaCameraBridge with javaCameraBridge2

**Comment by victoryforphil** [comment]
I don't see the issue. We run DogeCV on android versions ranging from 6.1 to 9.0 with 0 issues of this kind. Could you please detail the errors your receiving? In addition the underlying OpenCV layer is still EnderCV based.

**Comment by qmmp123** [comment]
Oh. My fall. I don't see camera preview in robot controller and dogecv does not work
