### ISSUE TITLE
Gradle sync failed.

### ISSUE THREAD

**Issue by AndreiMoiceanu29** [dogecv/DogeCV#30]
ERROR: Could not find method implementation() for arguments [project ':DogeCV'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by victoryforphil** [comment]
What Android Studio and Gradle Version are you running?

**Comment by SaiVeer04** [comment]
I have had the same error

**Comment by JFullerFPV** [comment]
Im having same problem

**Comment by Mosrod** [comment]
Hi, please read the Readme.md file and follow the instructions listed. The new version does not require any modules to be added. You will also need to delete the DogeCV folder from your project by opening the directory in explorer and deleting the DogeCV folder.
