### ISSUE TITLE
ERROR: Could not find method implementation() for arguments [DefaultProjectDependency{dependencyProject='project ':openCVLibrary3'', configuration='default'}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler. Open File

### ISSUE THREAD

**Issue by SaiVeer04** [dogecv/DogeCV#33]
I get this error when I downloaded it

**Comment by JFullerFPV** [comment]
Me too

**Comment by SPP3001** [comment]
I have also had this issue. I looked on stack and found some stuff saying that i need to "Replace implementation with 'compile' or 'api'". Neither of these work. It brings up the same error, but with "api" in place of "implementation"

**Comment by SaiVeer04** [comment]
you need to put the  code with implementation all the way at the bottom
