### ISSUE TITLE
Gradle Sync Issue with new SkyStone FTC SDK

### ISSUE THREAD

**Issue by nicobonik** [dogecv/DogeCV#35]
When i install the dogeCV libraries into my project with the updated Skystone SDK, i get this error.

ERROR: Failed to resolve: :RobotCore-release:
Affected Modules: DogeCV

does anyone know a way to fix this with the new SDK???

**Comment by nicobonik** [comment]
I accidentally cloned the DogeCV project into my root project folder, turns out Android Studio doesn't like that. I just moved it one directory back and re imported the libraries and everything works!

**Comment by MonroeBotics** [comment]
> I accidentally cloned the DogeCV project into my root project folder, turns out Android Studio doesn't like that. I just moved it one directory back and re imported the libraries and everything works!

Could you elaborate on how you fixed this issue? I'm not following the steps. Thanks!

**Comment by Mosrod** [comment]
Hi, please read the Readme.md file and follow the instructions listed. The new version does not require any modules to be added. You will also need to delete the DogeCV folder from your project by opening the directory in explorer and deleting the DogeCV folder.
