### ISSUE TITLE
ERROR: Failed to resolve: org.openftc:robotcore-stock:5.1 Show in Project Structure dialog Affected Modules: DogeCV

### ISSUE THREAD

**Issue by MonroeBotics** [dogecv/DogeCV#37]
I'm getting this even after I created a new FTC SDK with no edits at all

**Comment by scientifictouchftc** [comment]
I'm getting the same problem as well, we did the following steps: 
We downloaded and started a new project with skystone master. 
Then we downloaded DOGE CV and imported it as a module to the project. 
When the project built we had the same error showing up in the build status.

**Comment by Mosrod** [comment]
Hi, please read the Readme.md file and follow the instructions listed. The new version does not require any modules to be added. You will also need to delete the DogeCV folder from your project by opening the directory in explorer and deleting the DogeCV folder.
