### ISSUE TITLE
Will the OPENCVLibrary3 be in the Zip File as it was last year? 

### ISSUE THREAD

**Issue by scientifictouchftc** [dogecv/DogeCV#38]
When we downloaded the DOGE CV zip file, we didn't see the OPENCVLibrary3 in it so it also didn't show up in Android Studio. In last year's package the OPENCV library was there but this year it's not in the folder. Do you guys have any plan on putting it in the zip file? Also, which OpenCV library version is used for Doge CV.

**Comment by FROGbots-4634** [comment]
The OpenCV library is not included locally because it is pulled down through the dependency on EasyOpenCV, which in turn depends on and pulls down OpenCV-Repackaged.
(Note: I am the developer of EasyOpenCV and OpenCV-Repackaged)

**Comment by scientifictouchftc** [comment]
Ok thank you for letting us know and we will work according. I appreciate the help!
