### ISSUE TITLE
error: cannot access CameraStreamSource class file for org.firstinspires.ftc.robotcore.external.stream.CameraStreamSource not found

### ISSUE THREAD

**Issue by Rantsycancy** [dogecv/DogeCV#39]
When compiling the code this error occurs.
Am using test code and have followed installation instructions correctly.

**Comment by Rantsycancy** [comment]
Y there glitchy code???????!!!!!!!!!!!!!!!!1

**Comment by SumanthKondapalli** [comment]
How did you fix this?

**Comment by pdrey919** [comment]
> How did you fix this?

I would also like to know how to fix this. @SumanthKondapalli did you figure it out eventually?
